---
- name: Redeploy Kubernetes Service
  hosts: mostdock
  gather_facts: no
  
  vars:
    k8s_namespace: "default"
    deployment_name: "my-service"
    kubeconfig_path: "/home/ansible/.kube/config"
    
  tasks:
    - name: Verify kubectl connectivity
      command: kubectl --kubeconfig={{ kubeconfig_path }} get nodes
      register: nodes
      changed_when: false
    
    - name: Check if deployment exists
      command: >
        kubectl --kubeconfig={{ kubeconfig_path }}
        get deployment {{ deployment_name }}
        -n {{ k8s_namespace }}
      register: deployment_exists
      changed_when: false
      failed_when: false
      
    - name: Fail if deployment doesn't exist
      fail:
        msg: "Deployment {{ deployment_name }} not found in namespace {{ k8s_namespace }}"
      when: deployment_exists.rc != 0
    
    - name: Restart deployment
      command: >
        kubectl --kubeconfig={{ kubeconfig_path }}
        rollout restart deployment/{{ deployment_name }}
        -n {{ k8s_namespace }}
      register: rollout_result

    - name: Wait for rollout
      command: >
        kubectl --kubeconfig={{ kubeconfig_path }}
        rollout status deployment/{{ deployment_name }}
        -n {{ k8s_namespace }}
        --timeout=5m
      register: rollout_status
      
    - name: Get pod status
      command: >
        kubectl --kubeconfig={{ kubeconfig_path }}
        get pods -n {{ k8s_namespace }}
      register: pod_status
      changed_when: false
      
    - name: Display result
      debug:
        msg:
          - "Rollout: {{ rollout_status.stdout }}"
          - "Pods: {{ pod_status.stdout }}"